Introduce Credential Response Encryption policy.
eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt pull request #173
Opened 2024-03-22 12:18 UTC by dzarras

Closes #171

2024-03-22 17:14 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
> +                val maybeSpec = responseEncryptionSpecFactory(supportedAlgorithmsAndMethods, config.keyGenerationConfig)
Please wrap this into `runCatching{ ... }.getONull()` block.
Even the default implementation of `responseEncryptionSpecFactory` raises in some cases exception.

2024-03-22 17:15 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt
> +                when (config.credentialResponseEncryptionPolicy) {
Do we need the `when` at this point?
I don't think so

2024-03-22 17:16 UTC, babisRoutis requested changes
@dzarras Can you please tackle the comments?

2024-03-28 12:58 UTC, vafeini commented
We need the following 2 unit tests to be added:
- when wallet mandates encrypted responses but issuer does not then excpetion ResponseEncryptionRequiredByWalletButNotSupportedByIssuer is thrown
- when wallet mandates encrypted responses but no cryptographic can be generated WalletRequiresCredentialResponseEncryptionButNoCryptoMaterialCanBeGenerated is thrown

2024-03-28 13:05 UTC, vafeini submitted a review, later dismissed

2024-03-29 07:29 UTC, babisRoutis requested changes
@dzarras Can you please implement in this PR the first solution of
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/issues/171#issuecomment-2025383657

2024-03-29 08:07 UTC, dzarras commented
> * WalletRequiresCredentialResponseEncryptionButNoCryptoMaterialCanBeGenerated

Added.

2024-03-29 08:09 UTC, dzarras commented
@babisRoutis 

> Can you please implement in this PR the first solution of [#171 (comment)](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/issues/171#issuecomment-2025383657)

Done. Please check.

2024-03-29 14:25 UTC, vafeini approved these changes

2024-03-30 07:40 UTC, babisRoutis approved these changes

2024-03-30 07:40 UTC, merged